### ISSUE TITLE
Помогите

### ISSUE THREAD

**Issue by Partos1** [SavokBS/BackendRaider#2]
Я вставил API_ID и API_HASH свой, но я не пойму, что значит:
Enter first name:
Типо я должен свое имя вставить?
И еще, я вот пишу ,допустим, свое имя и спустя время, меня снова спрашивает мое имя.
И что делает скрипт?

**Comment by Partos1** [comment]
И что вообще делает скрипт?

**Comment by SavokBS** [comment]
если хочешь не вводить каждый раз новое имя, измени client.py в папке pyrogram’a
